const express = require('express')
const router = express.Router()

router.use('/admin/users', require('./admin/users'))
router.use('/admin/customers', require('./admin/customers'))
router.use('/admin/bots', require('./admin/bots'))
router.use('/admin/faqs', require('./admin/faqs'))
router.use('/admin/events-categories', require('./admin/events-categories'))
router.use('/admin/promoters', require('./admin/promoters'))
router.use('/admin/customer-bot-chats', require('./admin/customer-bot-chats'))
router.use('/admin/customer-bots', require('./admin/customer-bots'))
router.use('/admin/customer-events', require('./admin/customer-events'))
router.use('/admin/emails', require('./admin/emails'))
router.use('/admin/event-occurrences', require('./admin/event-occurrences'))
router.use('/admin/event-prices', require('./admin/event-prices'))
router.use('/admin/events', require('./admin/events'))
router.use('/admin/languages', require('./admin/languages'))
router.use('/admin/promoter-spots', require('./admin/promoter-spots'))
router.use('/admin/spots', require('./admin/spots'))
router.use('/admin/towns', require('./admin/towns'))
router.use('/admin/features-titles', require('./admin/features-titles'))
router.use('/customer/features-titles', require('./customer/features-titles'))
router.use('/customer/faqs', require('./customer/faqs'))
router.use('/admin/hero', require('./admin/hero'))
router.use('/customer/hero', require('./customer/hero'))
router.use('/admin/card', require('./admin/card'))
router.use('/customer/card', require('./customer/card'))
router.use('/admin/subscription', require('./admin/subscription'))
router.use('/customer/subscription', require('./customer/subscription'))
router.use('/customer/chats', require('./customer/chats'))
router.use('/customer/products/search', require('./customer/search'))

module.exports = router
